### ISSUE TITLE
helmet error

### ISSUE THREAD

**Issue by puncsky** [puncsky/onefx#148]
2020-10-30T19:38:26.055313+00:00 app[web.1]:   Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
2020-10-30T19:38:26.055313+00:00 app[web.1]:       at ServerResponse.setHeader (_http_outgoing.js:470:11)
2020-10-30T19:38:26.055331+00:00 app[web.1]:       at xDnsPrefetchControlMiddleware (/app/node_modules/helmet/dist/middlewares/x-dns-prefetch-control/index.js:7:13)
2020-10-30T19:38:26.055333+00:00 app[web.1]:       at internalNext (/app/node_modules/helmet/dist/index.js:75:13)
2020-10-30T19:38:26.055333+00:00 app[web.1]:       at helmet (/app/node_modules/helmet/dist/index.js:77:9)
2020-10-30T19:38:26.055334+00:00 app[web.1]:       at Promise (internal/util.js:274:30)
2020-10-30T19:38:26.055334+00:00 app[web.1]:       at new Promise (<anonymous>)
2020-10-30T19:38:26.055334+00:00 app[web.1]:       at helmet (internal/util.js:273:12)
2020-10-30T19:38:26.055335+00:00 app[web.1]:       at middleware (/app/node_modules/koa-helmet/lib/koa-helmet.js:11:12)
2020-10-30T19:38:26.055335+00:00 app[web.1]:       at postFunc (/app/node_modules/onefx/src/middleware/middleware.ts:48:15)
2020-10-30T19:38:26.055336+00:00 app[web.1]:       at /app/node_modules/onefx/src/middleware/middleware.ts:91:13
2020-10-30T19:38:26.055336+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by puncsky** [comment]
just disable koa-helmet for proxy endpoint
